version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    restart: always
    working_dir: /var/www
    volumes:
      - ./src:/var/www
  web:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: always
    ports:
      - 8081:81
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d/
  